services:
  postgres-cart: # service name must match the hostname in .env file.
    image: postgres:17.3
    container_name: postgres-cart
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_HOST_PORT}:${DATABASE_DOCKER_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: go-app-cart
    build:
      context: ../../
      dockerfile: deployments/dev/Dockerfile
    ports:
      - 8084:1323
    volumes:
      - ../../:/app # Important to bind/mount codebase dir to /app dir for live reload
    depends_on:
      postgres-cart:
        condition: service_healthy

volumes:
  postgres-data:
